### PR TITLE
Replace boolean expressions with if

### LINKED ISSUE #33: Unminify boolean expressions
Many obfuscators/minifiers convert if statements to these sorts of boolean expression chains which makes it hard to read:
```js
c.classes[t] && e.classIndex != t && (e.classIndex = t, e.updateItems(c, l, !0));
// -->
if (c.classes[t] && e.classIndex != t)
  e.classIndex = t, e.updateItems(c, l, true);
```
(and similar for `||`)

Is it ok if I PR this one for now? 🙂 

The goal is to combine it later with a few other modules (sequence to statements, [DeMorgan's law](https://github.com/nicoespeon/abracadabra/blob/main/REFACTORINGS.md#invert-boolean-logic), [yoda conditions](https://eslint.org/docs/latest/rules/yoda)):
```js
!o || c.oldGameTimer || 'skip' == c.gameTimer || 0 < c.endTimer || 'inf' == c.endTimer || (c.oldGameTimer = c.gameTimer,
                            c.gameTimer = 0);
// -->
if (o && !c.oldGameTimer && c.gameTimer != 'skip' && c.endTimer <= 0 && c.endTimer != 'inf') {
  c.oldGameTimer = c.gameTimer;
  c.gameTimer = 0;
}
```

### PR DESCRIPTION
**Pull request by j4k0xb**
closes #33

### CODE REVIEW

**Comment by BenBaryoPX** [comment]
Please update the `resources/*-deob.js` files to match the new deobfuscation output

**Comment by j4k0xb** [comment]
image
just came across a few weirder examples in localProxies.js-deob.js, do you think it's better to reorder the logical expressions to not require () grouping, merge the ifs later or just keep it that way?

**Comment by ctrl-escp** [comment]
> image just came across a few weirder examples in localProxies.js-deob.js, do you think it's better to reorder the logical expressions to not require () grouping, merge the ifs later or just keep it that way?

I've actually already reviewed all of the changes and I think they look fine.
Perhaps wrapping the if's consequent with a BlockStatement will improve readability?

**Review by BenBaryoPX — APPROVED** [review]
Nice work

**Pull request merged**
